module.exports = {
    'Inherited': 0,
    'DBObject': 1,
    'Struct': 2,
    'Pointer': 3,
    'Array': 4,
    'String': 6,
    'CString': 7,
    'Enum': 8,
    'FileReference': 9,
    'Boolean': 10,
    'Byte': 11,
    'UnsignedByte': 12,
    'Short': 13,
    'UnsignedShort': 14,
    'Integer': 15,
    'UnsignedInteger': 16,
    'UnsignedLong': 17,
    'Long': 18,
    'Float32': 19,
    'Float64': 20,
    'Guid': 21,
    'Sha1': 22,
    'ResourceReference': 23,
    'Delegate': 24,
    'TypeReference': 25,
    'BoxedValueReference': 26
};